"""Create books table

Revision ID: 08ae62ee97a2
Revises: a39599ef2649
Create Date: 2025-12-24 23:18:37.718529

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "08ae62ee97a2"
down_revision: str | None = "a39599ef2649"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
